### ISSUE TITLE
Broken JSON from gin-repod objectToWire

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/gin-repo#31]
Entry ID [here](https://github.com/G-Node/gin-repo/blob/07f2bbad7e34a1efcde59ebe230b0942cf7957b6/cmd/gin-repod/repo.go#L507) is missing a comma:

`out.WriteString(fmt.Sprintf("%q: %q\n", "id", entry.ID))`

Mode [here](https://github.com/G-Node/gin-repo/blob/07f2bbad7e34a1efcde59ebe230b0942cf7957b6/cmd/gin-repod/repo.go#L509) has a comma too many:

`out.WriteString(fmt.Sprintf("%q: \"%08o\",\n", "mode", entry.Mode))`

**Comment by gicmo** [comment]
SEND PATCHES! :D ... I am on it (:
