### ISSUE TITLE
Verified commits break tests

### ISSUE THREAD

**Issue by cgars** [G-Node/gin-repo#49]
In some cases (see eg. [here](https://travis-ci.org/G-Node/gin-repo/jobs/171071493) and when verified commits get packed the pack_test.go test, which tests against the repository it is in if i get it correctly, does fail. 

Ill confess that Git and verified commits are a complex issue (see [here](https://git-scm.com/book/tr/v2/Git-Tools-Signing-Your-Work#Everyone-Must-Sign) and [here](https://mikegerwitz.com/papers/git-horror-story) and it might well be that I should not sign my commits whatsoever, at least not if not everybody does so, however, i guess signed commits and Pack files might become an issue again at some point in time.

As a quick "fix": Shall i remove (rewrite) the signed commits for the time being? 
Ideas @gicmo @mpsonntag ?

**Comment by gicmo** [comment]
I filed issue #50 for this. Shouldn't be to hard to support this. I guess the same applies to tags, btw.

**Comment by cgars** [comment]
>  I guess the same applies to tags, btw.
Indeed and signed tags are the more relevant (because they are actually used by people) issue anyhow

**Comment by cgars** [comment]
Fixed by #52 Finally be adressed with #50
